### ISSUE TITLE
What about adding alos one orbisgis-parents-snaphot

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisparents#23]
to avoid some conflicts ;-)

**Comment by ebocher** [comment]
OrbisGIS parent is looking for a stable version of H2GIS 2.0.0... this version doesn't exist yet.
see 
https://jenkins.orbisgis.org/job/orbisparent/ and
https://github.com/orbisgis/orbisgis-parents/blob/master/orbisparent/pom.xml#L56

**Comment by SPalominos** [comment]
I think we can use the same pom by with different qualifiers :
 - `SNAPSHOT` when at least one of the dependencies/plugins are in `SNAPSHOT` state.
 - `RC-X` when there is no `SNAPSHOT` but at least one `RC`
 - Nothing (Release version) when all the dependencies/plugin are in Release version.

For version you can see the [Readme.md](https://github.com/orbisgis/orbisgis-parents/blob/master/orbisparent/README.md)
